Convert to plugin
discourse/discourse-onboarding-banner pull request #1
Opened 2021-11-19 22:55 UTC by jbrw

2021-11-20 11:46 UTC, CvX requested changes
I might have jump the gun on the review 😅 Anyway, a todo list won't hurt 😛

In addition to inline suggestions, can you update package.json and .gitignore, and add .github/workflows, .prettierc, .rubocop.yml, Gemfile, Gemfile.lock (see https://github.com/discourse/discourse-plugin-skeleton/), and rename *.es6 files to *.js? 😃

2021-11-20 11:46 UTC, CvX commented on plugin.rb
> +
```suggestion
# transpile_js: true

```

2021-11-20 11:46 UTC, CvX commented on plugin.rb
> +# url:https://github.com/discourse/discourse-onboarding-banner
```suggestion
# url: https://github.com/discourse/discourse-onboarding-banner
```

2021-11-20 11:46 UTC, CvX commented on plugin.rb
> +PLUGIN_NAME ||= 'DiscourseOnboardingBanner'
```suggestion
PLUGIN_NAME = 'DiscourseOnboardingBanner'
```

2021-11-20 11:46 UTC, CvX commented on assets/javascripts/discourse/templates/components/onboarding-banner.hbs
> +</div>
```suggestion
  <div class="onboarding-banner-content">
    {{html-safe cooked}}
    {{d-button icon="times" action=(action "dismissOnboarding")}}
  </div>
```

2021-11-20 11:46 UTC, CvX commented on assets/javascripts/discourse/components/onboarding-banner.js.es6
> +
```suggestion
  isLoading: true,

```

2021-11-20 11:46 UTC, CvX commented on assets/javascripts/discourse/components/onboarding-banner.js.es6
> +    dismissOnboarding() {
Please use `@action` decorator 😃

2021-11-20 11:46 UTC, CvX commented on test/javascripts/acceptance/discourse-onboarding-banner-test.js.es6
> +});
```suggestion
import { acceptance } from "discourse/tests/helpers/qunit-helpers";
import { test } from "qunit";
import { visit } from "@ember/test-helpers";

acceptance("DiscourseOnboardingBanner", function (needs) {
  needs.user();

  test("DiscourseOnboardingBanner works", async assert => {
    await visit("/admin/plugins/discourse-onboarding-banner");

    assert.ok(false, "it shows the DiscourseOnboardingBanner button");
});
```

And the assertion needs to be replaced with the real thing 😃

2021-11-23 00:00 UTC, CvX reviewed
Just couple more things 😃

2021-11-23 00:01 UTC, CvX commented on test/javascripts/acceptance/discourse-onboarding-banner-test.js
> +import { visit } from "@ember/test-helpers";
Oh, and `exists` (and visible/invisible) needs to be imported from qunit-helpers

2021-11-23 16:38 UTC, jbrw commented on test/javascripts/acceptance/discourse-onboarding-banner-test.js
> +      !exists(".onboarding-banner-content:visible"),
Neat! I wasn't aware of `invisible()`/`visible()`.

2021-11-23 16:43 UTC, CvX commented on assets/javascripts/discourse/components/onboarding-banner.js
> +        })
```suggestion
            this.set("cooked", cachedTopic.attrs.cooked);
        })
      }
```

Oops, I broke the code :P

2021-11-23 17:12 UTC, jbrw commented on assets/javascripts/discourse/components/onboarding-banner.js
> +      .catch(() => {});
That was my bad - the error that was being thrown was due to a bad stubbed response. Fixing that cleared up the error that was causing the issues.

2021-11-23 17:32 UTC, CvX approved these changes

2021-11-23 18:17 UTC, jbrw commented
Thank you @CvX for helping get this cleaned up and ready to ship!

2021-11-23 18:17 UTC, merged